version: "3.1"

services:
  frontend_one:
    build: ./frontend_one
    container_name: frontend_one
    hostname: frontend_one
    restart: unless-stopped
    ports:
      - "8001:80"

  frontend_two:
    build: ./frontend_two
    container_name: frontend_two
    hostname: frontend_two
    restart: unless-stopped
    ports:
      - "8002:80"

  frontend_three:
    build: ./frontend_three
    container_name: frontend_three
    hostname: frontend_three
    restart: unless-stopped
    ports:
      - "8003:80"

  th_ngnix_gateway:
    build: ./reverse-proxy-config/
    container_name: th_ngnix_gateway
    hostname: th_ngnix_gateway
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - frontend_one
      - frontend_two
      - frontend_three

networks:
  default:
